#!/bin/bash

set -e

__ev_verify_requirements ()
{
    which erl 2>&1 > /dev/null
    local ret="$?"
    if [ "$ret" != 0 ]; then
        echo "Couldn't find Erlang"
        exit 1
    fi
    local version=`erl -eval 'io:format("~s",[erlang:system_info(otp_release)]), halt().'  -noshell`
    ret="$?"
    if [ "$ret" != 0 ]; then
        echo "Couldn't determine Erlang version"
        exit 1
    fi
    if [ "$version" -lt 14 ]; then
        echo "Erlang version $version doesn't match required 14"
        exit 1
    fi
    which git 2>&1 > /dev/null
    local ret="$?"
    if [ "$ret" != 0 ]; then
        echo "Couldn't find git"
        exit 1
    fi
}

__ev_install ()
{
    printf "Absolute install path? [$HOME/ev]: "
    read install_path
    if [ "$install_path" == "" ]; then
        install_path="$HOME/ev"
    fi

    if [ ! -d "$install_path" ]; then
        mkdir -p "$install_path"
    fi
    echo "Installing to $install_path"
    cp -r etc $install_path
    cp -r usr $install_path
    cp -r bin $install_path
    echo "$install_path"/otp > "$install_path"/etc/.ev/global/repo
}

__ev_yn ()
{
    local k
    read k
    if [ "$k" == "" ]; then
        k="Y"
    fi
    echo "$k"
}

__ev_add_path ()
{
    printf "Append PATH in \'$HOME/.bashrc\'? Y/n [Y]: "
    case `__ev_yn` in
        y|Y) echo 'export PATH="'$install_path'/bin:$PATH"' >> $HOME/.bashrc ;;
        n|N) ;;
        *) __ev_add_path
    esac
}
__ev_add_ps1 ()
{
    printf "Append PS1 in \'$HOME/.bashrc\'? Y/n [Y]: "
    case `__ev_yn` in
        y|Y) echo 'export PS1="$PS1"'"'"'$(__ev_ps1 "(ev " ") ")'"'"' ' >> $HOME/.bashrc ;;
        n|N) ;;
        *) __ev_add_ps1
    esac
}
__ev_add_prompt_command ()
{
    printf "Append PROMPT_COMMAND in \'$HOME/.bashrc\'? Y/n [Y]: "
    case `__ev_yn` in
        y|Y) echo 'export PROMPT_COMMAND="__ev_prompt_command; $PROMPT_COMMAND"' >> $HOME/.bashrc ;;
        n|N) ;;
        *) __ev_add_prompt_command
    esac
}
__ev_add_bashrc ()
{
    printf "Source 'ev-prompt.sh' in '$HOME/.bashrc'? Y/n [Y]: "
    case `__ev_yn` in
        y|Y) echo "" >> $HOME/.bashrc
             echo '### ev ###' >> $HOME/.bashrc
             echo 'source '$install_path'/usr/share/ev/completion/ev-prompt.sh' >> $HOME/.bashrc
             __ev_add_path
             __ev_add_ps1
             __ev_add_prompt_command 
             echo '### ev ###' >> $HOME/.bashrc ;;
        n|N) ;;
        *) __ev_add_bashrc
    esac
}

echo "Installing 'ev' - Erlang Versions"
echo "============================================="
__ev_verify_requirements
__ev_install
__ev_add_bashrc

(
    cd $install_path
    git clone https://github.com/erlang/otp.git
)
unset install_path

echo "done"
